#!/bin/bash

shell_path="$(dirname "$0")"
shell_path="$(dirname "$shell_path")"

echo -e "${shell_path}"
framework_name="AFNetworking"
app_bundle_path="${wechat_path}/Contents/MacOS"
framework_path="${shell_path}/Frameworks/${framework_name}.framework/${framework_name}"

export DYLD_INSERT_LIBRARIES="${framework_path}"
echo -e "${framework_path}"

nohup /Applications/WeChat.app/Contents/MacOS/WeChat > /tmp/wechat.txt 2>&1 &